# 예외처리

예외처리란 에러가 났을 때, 애플리케이션이 꺼지지 않고 **매뉴얼대로 행동하도록** 하는 것이다.

### 에러 발생 원인들

1. String 타입과 int 타입을 더했을 때
2. Text 위젯에 String 대신 null을 넣어줄 때
3. List의 길이가 3까지인데, 인덱싱에 4를 넣어서 범위 에러가 발생할 때
4. 네트워크 요청을 보냈는데 에러가 날 때

## try-catch 에러 원인 출력

---

```dart
try {
	List items = ["a","b","c"];
	print(items[3]);
} catch (e) {
	print("에러가 났다 ${e}");
} finally {
	print("실행 끝");
}
```

## try-catch 예상 가능 에러 설정

---

해당 에러가 발생했을 때 블록 내의 코드가 실행된다.

```dart
try {
	List items = ["a","b","c"];
	print(items[3]);
} on RangeError {
	print("범위 에러가 났다");
} finally {
	print("실행 끝");
}
```

에러 설정과 출력을 같이 해줄 수 있다. 뒤에 catch문을 같이 사용하면 된다.

```dart
try {
	List items = ["a","b","c"];
	print(items[3]);
} on RangeError catch (e) {
	print("범위 에러가 났다 ${e}");
} finally {
	print("실행 끝");
}
```

## try-catch 사용한 서버 데이터 갖고오기 예시

---

```dart
Dio dio = Dio();
String? messgae = "메세지 가져오기";
String result = "";

void getData() async {
  result = "";
  setState((){});
  try {
    var url = '주소';
    var res = await dio.get(url);
    result = res.data["item"]["name"];
  } on DioError catch (e) {
    result = e.message;
  } finally {
    setState((){});
  }
}
```
